name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # täglich um Mitternacht
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Linus72
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#000000&color_dots=#ebedf0,#c8c8c8,#969696,#5a5a5a,#000000
            dist/github-contribution-grid-snake-dark.svg?color_snake=#ffffff&color_dots=#161b22,#3a3a3a,#6e6e6e,#a8a8a8,#ffffff

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
